version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn start
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  build2:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -tag=docker-test .
      - run: |
          docker run -d --docker-test
          docker push docker-test
  # push-image:
    # docker:
    #   - image: circleci/node
    # steps:
    #   - attach_workspace:
    #     at: .
    #   - setup_remote_docker
    #   - run: |
    #       docker login -u $DOCKER_USER -p $DOCKER_PASS
    #       docker build -tag=docker-test .
    #   - run: |
    #       docker run -d --docker-test
    #       docker push docker-test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - build2:
          requires:
            - build